### ISSUE TITLE
Theme not applied to the terminal

### ISSUE THREAD

**Issue by jinyeom** [withastro/houston-vscode#1]
![image](https://user-images.githubusercontent.com/9257771/207510747-8d6e492b-2194-4bf1-b243-bae81e7082bd.png)

The theme doesn't seem to apply to the terminal. Great looking theme so far!

**Comment by natemoo-re** [comment]
Fixed in 6439074c058973218c66835fe7e5fba37c5d45b3 and released in v0.0.6!
