### ISSUE TITLE
Comments are hard to read when highlighted

### ISSUE THREAD

**Issue by saturnonearth** [withastro/houston-vscode#11]
Comments are hard to read when highlighted

![CleanShot 2022-12-23 at 15 26 28](https://user-images.githubusercontent.com/12503538/209402767-30c4af28-7819-4428-9344-8abd1991a6e6.png)

**Comment by delucis** [comment]
I believe this is now fixed!

<img width="255" alt="image" src="https://github.com/withastro/houston-vscode/assets/357379/cdd409af-25d9-4e90-bfb2-326de01a641c">
