### ISSUE TITLE
Highlight whitespace so that it can be more easily seen

### ISSUE THREAD

**Issue by LucyBufton-zz** [withastro/houston-vscode#17]
I really like the Houston colour theme, but could whitespace have a greater contrast so that it can be more easily seen? 

Thanks

Lucy

**Comment by VoxelMC** [comment]
Hello @LucyBufton-zz!

Does the change in this merged PR (#24) fix this issue?

**Comment by natemoo-re** [comment]
Thanks @VoxelMC! I personally think #24 resolved this issue, but let's reopen this if not everyone agrees. Thanks!
