### ISSUE TITLE
cause of unhappiness

### ISSUE THREAD

**Issue by mvolkmann** [withastro/houston-vscode#34]
When the Houston face is not smiling, how can I determine what the issue is that it sees?

**Comment by delucis** [comment]
Houston responds to the number of issues in the VS Code “Problems” panel. You can show the panel with <kbd>Cmd + Shift + M</kbd> (Mac) or <kbd>Ctrl + Shift + M</kbd> (Windows/Linux).

**Comment by mvolkmann** [comment]
Thanks @delucis!
