### ISSUE TITLE
Unable to view the Houston Bot

### ISSUE THREAD

**Issue by RangerDevv** [withastro/houston-vscode#8]
Hello! I have been using the Astro theme for quite a while. However, I am unable to view/enable the Houston Mascot. I am not sure if it is my limited knowledge or a known bug. I am using VS code as my editor. Here is a picture.
![image](https://user-images.githubusercontent.com/66392962/208964906-92352554-caa9-474c-a90a-ed13d1d36627.png)
![image](https://user-images.githubusercontent.com/66392962/208964975-3f5049d8-cbd7-4809-9f67-b7efa318b257.png)
Thank you so much.
-Ranger

**Comment by dastaten** [comment]
Doesn't show for me either.

**Comment by noClaps** [comment]
If you right click on Timeline, do you see Houston as one of the options in the menu?

**Comment by RangerDevv** [comment]
This issue has been resolved. The bot was for some reason on my second side panel so I was unable to see it. To fix it you can go to view and enable the option to view the second side panel
